// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orbtoohygwtklxcdjyfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yYnRvb2h5Z3d0a2x4Y2RqeWZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTk2OTQsImV4cCI6MjA3MzM3NTY5NH0.P4hGlmZp1HaznvcvIJ_abmLunOvdA44i2yvfu5m6LH4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});