
export const mockAppointments = [
  {
    id: '1',
    patientName: 'John Doe',
    patientPhone: '+1234567890',
    doctor: 'Dr. Smith',
    room: 'Room 101',
    date: '2024-02-05',
    time: '09:00',
    duration: 30,
    type: 'consultation',
    status: 'confirmed',
    reason: 'Regular checkup',
    notes: 'Patient reports feeling well'
  },
  {
    id: '2',
    patientName: 'Jane Smith',
    patientPhone: '+1234567891',
    doctor: 'Dr. Johnson',
    room: 'Room 102',
    date: '2024-02-05',
    time: '09:30',
    duration: 45,
    type: 'follow-up',
    status: 'pending',
    reason: 'Blood pressure follow-up',
    notes: 'Check medication effectiveness'
  },
  {
    id: '3',
    patientName: 'Mike Johnson',
    patientPhone: '+1234567892',
    doctor: 'Dr. Williams',
    room: 'Room 201',
    date: '2024-02-05',
    time: '10:00',
    duration: 60,
    type: 'consultation',
    status: 'completed',
    reason: 'Joint pain assessment',
    notes: 'X-ray ordered'
  },
  {
    id: '4',
    patientName: 'Sarah Wilson',
    patientPhone: '+1234567893',
    doctor: 'Dr. Brown',
    room: 'Room 102',
    date: '2024-02-05',
    time: '10:30',
    duration: 30,
    type: 'routine-check',
    status: 'cancelled',
    reason: 'Annual physical',
    notes: 'Rescheduled to next week'
  },
  {
    id: '5',
    patientName: 'David Lee',
    patientPhone: '+1234567894',
    doctor: 'Dr. Smith',
    room: 'Room 101',
    date: '2024-02-05',
    time: '11:00',
    duration: 30,
    type: 'follow-up',
    status: 'no-show',
    reason: 'Diabetes follow-up',
    notes: 'Patient did not show up'
  },
  {
    id: '6',
    patientName: 'Emily Davis',
    patientPhone: '+1234567895',
    doctor: 'Dr. Johnson',
    room: 'Room 201',
    date: '2024-02-06',
    time: '09:00',
    duration: 30,
    type: 'consultation',
    status: 'confirmed',
    reason: 'Headache consultation',
    notes: 'Recurring headaches for 2 weeks'
  },
  {
    id: '7',
    patientName: 'Robert Chen',
    patientPhone: '+1234567896',
    doctor: 'Dr. Williams',
    room: 'Room 102',
    date: '2024-02-06',
    time: '14:00',
    duration: 45,
    type: 'emergency',
    status: 'pending',
    reason: 'Acute back pain',
    notes: 'Urgent consultation needed'
  },
  {
    id: '8',
    patientName: 'Lisa Anderson',
    patientPhone: '+1234567897',
    doctor: 'Dr. Brown',
    room: 'Room 201',
    date: '2024-02-07',
    time: '15:30',
    duration: 30,
    type: 'follow-up',
    status: 'confirmed',
    reason: 'Post-surgery checkup',
    notes: 'Check wound healing progress'
  }
];
